In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a[2]

3

In [4]:
import time
import sys

In [5]:
l = range(1000)
print(sys.getsizeof(5) *len(l))

28000


In [6]:
array = np.arange(1000)
print(array.size*array.itemsize)  ##numpy is using less space as compair to list

4000


In [7]:
size = 1000000
l1 = range(size)
l2 = range(size)

a1 = np.array(size)
a2 = np.array(size)

start = time.time()
## python list
result = [(x+y) for x , y in zip(l1,l2)]
print ("python list time" , (time.time()-start)*1000) ## for time in milisecond
start = time.time()
result = a1 + a2
print ("numpy list time" , (time.time()-start)*1000) ## for time in milisecond

python list time 414.5045280456543
numpy list time 30.960559844970703


In [8]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
a1+a2

array([5, 7, 9])

In [9]:
a1*a2

array([ 4, 10, 18])

In [10]:
a1/a2

array([0.25, 0.4 , 0.5 ])

In [11]:
a1%a2

array([1, 2, 3], dtype=int32)

In [12]:
a = np.array([[1,2],[3,4],[5,6]]) ##2D array
a.ndim

2

In [13]:
a.itemsize   ## iteam size is 4 bits

4

In [14]:
a.dtype

dtype('int32')

In [15]:
a = np.array([[1,2],[3,4],[5,6]],dtype = np.float64) ##2D array

In [16]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [17]:
a.itemsize

8

In [18]:
a.size

6

In [19]:
a.shape

(3, 2)

In [20]:
a = np.array([[1,2] , [3,4], [5,6]] , dtype = complex)

In [21]:
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [22]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.arange(1,5)

array([1, 2, 3, 4])

In [25]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [26]:
np.linspace(1,5,10)  ## 10 numbers between 1 and 5 linearly spaced

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [27]:
a = np.array([[1,2],[3,4],[5,6]])
a.shape

(3, 2)

In [28]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
a.ravel()  ## flaten array ( one demination array)

array([1, 2, 3, 4, 5, 6])

In [30]:
a.min()

1

In [31]:
a.max()

6

In [32]:
a.sum()

21

In [33]:
a.sum(axis = 0)  ## sum colums

array([ 9, 12])

In [34]:
a.sum(axis = 1)

array([ 3,  7, 11])

In [35]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [36]:
np.std(a) ##standerd deviation

1.707825127659933

In [37]:
a = np.array([[1,2],[3,4],[5,6]])
b = np.array([[5,6] , [7,8]])

In [38]:
a.dot(b)

array([[19, 22],
       [43, 50],
       [67, 78]])

In [39]:
a[0:2]

array([[1, 2],
       [3, 4]])

In [40]:
a[0:2,1]

array([2, 4])

In [41]:
a[-1, 0:2]

array([5, 6])

In [45]:
a[:,1:2]  ## starting : show that all the rows to be included

array([[2],
       [4],
       [6]])

In [46]:
for row in a:
    print(row)

[1 2]
[3 4]
[5 6]


In [47]:
for cell in a.flat:
    print(cell)

1
2
3
4
5
6
