In [1]:
import numpy as np

In [2]:
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)

In [3]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [4]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [5]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [6]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [7]:
a = np.arange(30).reshape(2,15)

In [8]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [10]:
result = np.hsplit(a,3)   ##spliting list into 3 different list
result

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [11]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [15]:
b = a > 4  ## verifing the condition will all the elements and storing it in an array
b

array([[False, False, False, False, False,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True]])

In [16]:
a[b]  ## where ever it found true it return that value

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [17]:
a[b] = -1

In [18]:
a

array([[ 0,  1,  2,  3,  4, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]])

In [19]:
for x in np.nditer(a , order = 'C'):  ## same as using flatten
    print(x)

0
1
2
3
4
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1


In [20]:
for x in np.nditer(a , order = 'F'):  ## to print in coloums
    print(x)

0
-1
1
-1
2
-1
3
-1
4
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1
-1


In [21]:
for x in np.nditer(a , order = 'F' , flags = ['external_loop']):  ## print a coloums of values
    print(x)

[ 0 -1]
[ 1 -1]
[ 2 -1]
[ 3 -1]
[ 4 -1]
[-1 -1]
[-1 -1]
[-1 -1]
[-1 -1]
[-1 -1]
[-1 -1]
[-1 -1]
[-1 -1]
[-1 -1]
[-1 -1]


In [23]:
for x in np.nditer(a , op_flags = ['readwrite']):   ## square of every element
    x[...] = x*x

In [24]:
a

array([[ 0,  1,  4,  9, 16,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1]])

In [58]:
b = np.arange(30).reshape(2,15)

In [59]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [60]:
for x,y in np.nditer([a,b]):  ## demainction of array must be same or at leat 1 is 1 
    print(x,y)

0 0
1 1
4 2
9 3
16 4
1 5
1 6
1 7
1 8
1 9
1 10
1 11
1 12
1 13
1 14
1 15
1 16
1 17
1 18
1 19
1 20
1 21
1 22
1 23
1 24
1 25
1 26
1 27
1 28
1 29
